package com.example.weatherapp.general.usecases

import com.example.weatherapp.general.usecases.weather.models.*

fun getFakeWeatherForToday(): WeatherForToday {
    return WeatherForToday(
        clouds = 0,
        dewPoint = 0.0,
        date = "00.00.00",
        feelsLike = 0.0,
        humidity = 0,
        pressure = 0,
        sunrise = 0,
        sunset = 0,
        temperature = "0",
        uvi = 0.0,
        visibility = 0,
        aboutWeather = getWeatherList(),
        windDegrees = 0,
        windGust = 0.0,
        windSpeed = 0.0,
        weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png",
        weatherDescription = "Описание",
    )
}

private fun getWeatherList(): List<AboutWeather> {
    return listOf<AboutWeather>(
        AboutWeather(
            description = "Описание",
            icon = "04d",
            id = 0,
            main = "main"
        )
    )
}

 fun getFakeWeatherForDay(): List<WeatherForDay> {
    val feelsLike = FeelsLike(
        day = 0.0,
        evening = 0.0,
        morning = 0.0,
        night = 0.0
    )

    return listOf(
        WeatherForDay(
            clouds = 0,
            dewPoint = 0.0,
            date = "00.00.00",
            feelsLike = feelsLike,
            humidity = 0,
            moonPhase = 0.0,
            moonrise = 0,
            moonSet = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            rain = 0.0,
            snow = 0.0,
            sunrise = 0,
            sunset = 0,
            uvi = 0.0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherForHour = getWeatherForHour(),
            daytimeTemperature = "0",
            eveningTemperature = "0",
            maxTemperature = "0",
            minTemperature = "0",
            morningTemperature = "0",
            nighttimeTemperature = "0",
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png",
        ),
        WeatherForDay(
            clouds = 0,
            dewPoint = 0.0,
            date = "00.00.00",
            feelsLike = feelsLike,
            humidity = 0,
            moonPhase = 0.0,
            moonrise = 0,
            moonSet = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            rain = 0.0,
            snow = 0.0,
            sunrise = 0,
            sunset = 0,
            uvi = 0.0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherForHour = getWeatherForHour(),
            daytimeTemperature = "0",
            eveningTemperature = "0",
            maxTemperature = "0",
            minTemperature = "0",
            morningTemperature = "0",
            nighttimeTemperature = "0",
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png",
        ),
        WeatherForDay(
            clouds = 0,
            dewPoint = 0.0,
            date = "00.00.00",
            feelsLike = feelsLike,
            humidity = 0,
            moonPhase = 0.0,
            moonrise = 0,
            moonSet = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            rain = 0.0,
            snow = 0.0,
            sunrise = 0,
            sunset = 0,
            uvi = 0.0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherForHour = getWeatherForHour(),
            daytimeTemperature = "0",
            eveningTemperature = "0",
            maxTemperature = "0",
            minTemperature = "0",
            morningTemperature = "0",
            nighttimeTemperature = "0",
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png",
        ),
        WeatherForDay(
            clouds = 0,
            dewPoint = 0.0,
            date = "00.00.00",
            feelsLike = feelsLike,
            humidity = 0,
            moonPhase = 0.0,
            moonrise = 0,
            moonSet = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            rain = 0.0,
            snow = 0.0,
            sunrise = 0,
            sunset = 0,
            uvi = 0.0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherForHour = getWeatherForHour(),
            daytimeTemperature = "0",
            eveningTemperature = "0",
            maxTemperature = "0",
            minTemperature = "0",
            morningTemperature = "0",
            nighttimeTemperature = "0",
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png",
        ),
        WeatherForDay(
            clouds = 0,
            dewPoint = 0.0,
            date = "00.00.00",
            feelsLike = feelsLike,
            humidity = 0,
            moonPhase = 0.0,
            moonrise = 0,
            moonSet = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            rain = 0.0,
            snow = 0.0,
            sunrise = 0,
            sunset = 0,
            uvi = 0.0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherForHour = getWeatherForHour(),
            daytimeTemperature = "0",
            eveningTemperature = "0",
            maxTemperature = "0",
            minTemperature = "0",
            morningTemperature = "0",
            nighttimeTemperature = "0",
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png",
        ),
    )
}

private fun getWeatherForHour(): List<WeatherForHour> {
    return listOf(
        WeatherForHour(
            clouds = 0,
            dewPoint = 0.0,
            hour = "00.00.00",
            feelsLike = 0.0,
            humidity = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            snow = Snow(0.0),
            temperature = "0",
            uvi = 0.0,
            visibility = 0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png"
        ),
        WeatherForHour(
            clouds = 0,
            dewPoint = 0.0,
            hour = "00.00.00",
            feelsLike = 0.0,
            humidity = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            snow = Snow(0.0),
            temperature = "0",
            uvi = 0.0,
            visibility = 0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png"
        ),
        WeatherForHour(
            clouds = 0,
            dewPoint = 0.0,
            hour = "00.00.00",
            feelsLike = 0.0,
            humidity = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            snow = Snow(0.0),
            temperature = "0",
            uvi = 0.0,
            visibility = 0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png"
        ),
        WeatherForHour(
            clouds = 0,
            dewPoint = 0.0,
            hour = "00.00.00",
            feelsLike = 0.0,
            humidity = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            snow = Snow(0.0),
            temperature = "0",
            uvi = 0.0,
            visibility = 0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png"
        ),
        WeatherForHour(
            clouds = 0,
            dewPoint = 0.0,
            hour = "00.00.00",
            feelsLike = 0.0,
            humidity = 0,
            probabilityOfPrecipitation = 0.0,
            pressure = 0,
            snow = Snow(0.0),
            temperature = "0",
            uvi = 0.0,
            visibility = 0,
            aboutWeather = getWeatherList(),
            windDegrees = 0,
            windGust = 0.0,
            windSpeed = 0.0,
            weatherIcon = "http://openweathermap.org/img/w/" + "04d" + ".png"
        ),
    )
}